{
  "name": "wordpress-template",
  "region": "nyc",
  "services": [
    {
      "name": "wordpress",
      "github": {
        "repo": "Independent-Business-Group/wordpress-template",
        "branch": "main",
        "deploy_on_push": true
      },
      "build_command": "chmod +x .do/deploy.sh && ./.do/deploy.sh",
      "run_command": "heroku-php-apache2",
      "environment_slug": "php",
      "envs": [
        {
          "key": "DB_NAME",
          "value": "${wordpress_template.DATABASE}",
          "scope": "RUN_AND_BUILD_TIME",
          "type": "SECRET"
        },
        {
          "key": "DB_USER",
          "value": "${wordpress_template.USERNAME}",
          "scope": "RUN_AND_BUILD_TIME",
          "type": "SECRET"
        },
        {
          "key": "DB_PASSWORD",
          "value": "${wordpress_template.PASSWORD}",
          "scope": "RUN_AND_BUILD_TIME",
          "type": "SECRET"
        },
        {
          "key": "DB_HOST",
          "value": "${wordpress_template.HOSTNAME}",
          "scope": "RUN_AND_BUILD_TIME",
          "type": "SECRET"
        },
        {
          "key": "DB_PORT",
          "value": "${wordpress_template.PORT}",
          "scope": "RUN_AND_BUILD_TIME",
          "type": "SECRET"
        },
        {
          "key": "TABLE_PREFIX",
          "value": "wp_",
          "scope": "RUN_AND_BUILD_TIME"
        }
      ],
      "health_check": {
        "http_path": "/",
        "port": 8080,
        "initial_delay_seconds": 90,
        "period_seconds": 10,
        "timeout_seconds": 5,
        "success_threshold": 1,
        "failure_threshold": 3
      },
      "http_port": 8080,
      "instance_count": 1,
      "instance_size_slug": "apps-s-1vcpu-0.5gb"
    }
  ],
  "databases": [
    {
      "name": "wordpress-template",
      "engine": "MYSQL",
      "production": false,
      "cluster_name": "wordpress-mysql-cluster"
    }
  ]
}
