name: wordpress-customer-test
region: nyc

services:
  - name: wordpress
    github:
      repo: Independent-Business-Group/wordpress-template
      branch: main
      deploy_on_push: true
    build_command: chmod +x .do/deploy.sh && ./.do/deploy.sh
    run_command: heroku-php-apache2
    environment_slug: php
    envs:
      - key: DB_NAME
        value: customer_name
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_USER
        value: customer_name_user
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_PASSWORD
        value: Np2aCQWHdvL2wVwM97Jm0zEV5AykTXUi
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_HOST
        value: wordpress-mysql-cluster-do-user-28531160-0.i.db.ondigitalocean.com
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_PORT
        value: "25060"
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: TABLE_PREFIX
        value: customer_n_
        scope: RUN_AND_BUILD_TIME
    health_check:
      http_path: /
      port: 8080
      initial_delay_seconds: 90
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
